org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=128m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

# Add these lines to prevent JVM native crashes on Windows:
org.gradle.native=false
org.gradle.daemon=false
org.gradle.workers.max=2